### ISSUE TITLE
Translating ch17 (up to ch17-02)

### ISSUE THREAD

**Issue by joeljpresent** [Jimskapt/rust-book-fr#119]
I'm going to translate Chapter 17 (about OOP features of Rust) in French.

**Comment by Jimskapt** [comment]
Hi @joeljpresent, I suppose you don't plan anymore to translate this chapter ? (I'll be there soon)

**Comment by joeljpresent** [comment]
I have been busy since mid-November, but I will be able to work on Chapter 17 from next week onwards.
I have also translated Chapter 17-00 and most of Chapter 17-01.
So, I still plan to translate this chapter.

**Comment by Jimskapt** [comment]
Nice, great news ! So I will skip the whole ch17, then :smile: !

**Comment by Jimskapt** [comment]
Hello @joeljpresent, I hope you're safe despite the current events.

I'm currently in the process of finishing my translation work of this book, there is just missing ch17 and ch21 (appendix). I wondering if you are currently working on ch17, otherwise can I take over from you ?

(oh and by the way, the #176 was merged on `french-unreleased` branch which are used of [GitHub pages publication of the book](https://jimskapt.github.io/rust-book-fr/ch17-00-oop.html))

**Comment by joeljpresent** [comment]
I'm still working on ch17: I've finished ch17-01 (PR soon) and I've started ch17-02.
I'll do my best to finish the chapter before the end of April.

**Comment by Jimskapt** [comment]
Okay, thank you so much Joël, that would be awesome ! 😊

**Comment by joeljpresent** [comment]
Little update: I don't think I'll have the time to translate Chapter 17-03 (*Implementing an Object-Oriented Design Pattern*) before the end of the month, so you can take over ch17-03 from me.

However, I'm still working on Chapter 17-02 (about trait objects), and it will be ready next week.

**Comment by Jimskapt** [comment]
OK, thank you for your work and your feedback !
So I'm starting translation of ch17-03 right now 😉
