### ISSUE TITLE
Translating ch05

### ISSUE THREAD

**Issue by joeljpresent** [Jimskapt/rust-book-fr#33]
I'm going to translate chapter 05 (about structs) in French.

**Comment by Jimskapt** [comment]
Hello, i'm planning to continue the translation of the chapter 05 very soon, is it OK for you, @joeljpresent, or do you want to keep this part ?

**Comment by joeljpresent** [comment]
I've already translated Chapters 05-01 and 05-02 but I have not proofread them yet.
I can push them if you like.

**Comment by Jimskapt** [comment]
hey, it's nice to read this ! I was thinking you were stuck on ch05-00 !

So, if you think you can keep going, I will wait for you 😉 
Otherwise, yes please commit your work on your branch and then i will do a PR in order to merge and continue.
In each case, please say me what do you plan to do, please !

And if self-proofreading is too much for you, I'm here to do it so you can skip it ! 😉
